# Generated by Django 4.2.16 on 2024-09-29 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="goals",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="my_app.user"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="habits",
            name="user",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="my_app.user"
            ),
            preserve_default=False,
        ),
    ]
