# Generated by Django 4.2.16 on 2024-09-29 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("my_app", "0002_goals_user_habits_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="goal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="my_app.goals",
            ),
        ),
    ]
